import type { Permission, UserRole } from "@/types";

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  owner: [
    "dashboard.view",
    "pos.operate",
    "sales.view",
    "sales.create",
    "returns.create",
    "inventory.view",
    "inventory.manage",
    "inventory.adjust",
    "purchases.view",
    "purchases.manage",
    "suppliers.view",
    "suppliers.manage",
    "customers.view",
    "customers.manage",
    "prescriptions.view",
    "prescriptions.manage",
    "expenses.view",
    "expenses.manage",
    "employees.view",
    "employees.manage",
    "reports.view",
    "analytics.view",
    "settings.view",
    "settings.manage",
    "users.manage",
    "audit.view",
    "ai.use",
  ],
  administrator: [
    "dashboard.view",
    "pos.operate",
    "sales.view",
    "sales.create",
    "returns.create",
    "inventory.view",
    "inventory.manage",
    "inventory.adjust",
    "purchases.view",
    "purchases.manage",
    "suppliers.view",
    "suppliers.manage",
    "customers.view",
    "customers.manage",
    "prescriptions.view",
    "prescriptions.manage",
    "expenses.view",
    "expenses.manage",
    "employees.view",
    "employees.manage",
    "reports.view",
    "analytics.view",
    "settings.view",
    "settings.manage",
    "users.manage",
    "audit.view",
    "ai.use",
  ],
  manager: [
    "dashboard.view",
    "pos.operate",
    "sales.view",
    "sales.create",
    "returns.create",
    "inventory.view",
    "inventory.manage",
    "purchases.view",
    "purchases.manage",
    "suppliers.view",
    "suppliers.manage",
    "customers.view",
    "customers.manage",
    "prescriptions.view",
    "expenses.view",
    "employees.view",
    "reports.view",
    "ai.use",
  ],
  cashier: ["dashboard.view", "pos.operate", "sales.view", "sales.create", "returns.create", "customers.view", "customers.manage"],
  pharmacist: [
    "dashboard.view",
    "inventory.view",
    "prescriptions.view",
    "prescriptions.manage",
    "pos.operate",
    "customers.view",
    "ai.use",
  ],
  inventory_staff: ["dashboard.view", "inventory.view", "inventory.manage", "inventory.adjust", "purchases.view"],
};

export const ALL_ROLES: UserRole[] = [
  "owner",
  "administrator",
  "manager",
  "cashier",
  "pharmacist",
  "inventory_staff",
];

export function hasPermission(role: UserRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}
